language: java
sudo: false
jdk:
  - openjdk11

env:
  global:
    - CODECOV_TOKEN=:a4b5cf55-b019-4d4b-82b6-3f06443883f0

matrix:
  include:
    - jdk: openjdk11
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

after_success:
  - bash <(curl -s https://codecov.io/bash)